version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /opt/apps/nginx/html:/usr/share/nginx/html
      - /opt/apps/nginx/conf.d:/etc/nginx/conf.d
      - /opt/apps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/apps/nginx/log:/var/log/nginx
    networks:
      - common-net
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /opt/apps/mysql/datadir:/var/lib/mysql
      - /opt/apps/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - common-net
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /opt/apps/redis/data:/data
    networks:
      - common-net
  asynq:
    image: redis
    container_name: asynq
    restart: always
    volumes:
      - /opt/apps/asynq/data:/data
    networks:
      - common-net
  asynqmon:
    image: hibiken/asynqmon
    container_name: asynqmon
    restart: always
    depends_on:
      - asynq
    ports:
      - "8080:8080"
    networks:
      - common-net
    command: ["--redis-addr=asynq:6379"]

networks:
  common-net:
    external: true
